// LocalStorage persistence helpers for flashcard state management

const STORAGE_KEY = 'flashcards_app_state'

// Default sample deck for first-time visitors
const initialSampleDecks = [
  {
    id: 'sample-deck-1',
    groupName: 'React Fundamentals',
    groupDescription: 'Core React concepts including components, hooks, state management, and the virtual DOM.',
    groupImage: null,
    createdAt: new Date().toISOString(),
    terms: [
      {
        id: 'term-1',
        term: 'Virtual DOM',
        definition: 'An in-memory representation of the real DOM elements generated by React components before any changes are written to the browser.',
        image: null
      },
      {
        id: 'term-2',
        term: 'useState Hook',
        definition: 'A React Hook that lets you add state variables to functional components and re-render the component when state updates.',
        image: null
      },
      {
        id: 'term-3',
        term: 'Redux Toolkit',
        definition: 'The official, opinionated, batteries-included toolset for efficient Redux development with simplified store setup and slice reducers.',
        image: null
      }
    ]
  }
]

/**
 * Load persisted flashcards from browser localStorage
 * Falls back to initial sample deck if no data is found
 */
export const loadState = () => {
  try {
    const serializedState = localStorage.getItem(STORAGE_KEY)
    if (serializedState === null) {
      return initialSampleDecks
    }
    const parsed = JSON.parse(serializedState)
    return Array.isArray(parsed) ? parsed : initialSampleDecks
  } catch (error) {
    console.warn('Could not load flashcards state from localStorage:', error)
    return initialSampleDecks
  }
}

/**
 * Save updated flashcard list to browser localStorage
 */
export const saveState = (flashcards) => {
  try {
    const serializedState = JSON.stringify(flashcards)
    localStorage.setItem(STORAGE_KEY, serializedState)
  } catch (error) {
    console.error('Could not save flashcards state to localStorage:', error)
  }
}
